#
# Oracle Java 8 Dockerfile
#
# https://github.com/dockerfile/java
# https://github.com/dockerfile/java/tree/master/oracle-java8
#

# Pull base image.
FROM ubuntu:16.04

VOLUME /scigraph

RUN apt-get -y update && apt-get install -y software-properties-common python-software-properties

# Install Java.
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

# Install Maven.
RUN apt-get -y update && apt-get install -y maven

# Install Git.
RUN apt-get -y update && apt-get install -y git

# Install unzip.
RUN apt-get -y update && apt-get install -y unzip

# Define working directory.
WORKDIR /data
ADD target/generated-resources/monarch-server-config.yaml /data/

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

# add xvfb
RUN apt-get -y update && apt-get install -y xvfb
RUN apt-get -y update && apt-get install -y libxrender1
RUN apt-get -y update && apt-get install -y libxi6
RUN apt-get -y update && apt-get install -y libxtst6


# Define default command.
RUN git clone https://github.com/SciGraph/SciGraph.git /data/scigraph
RUN cd /data/scigraph && mvn install -DskipTests -DskipITs
#CMD cd /data/scigraph/SciGraph-services && mvn exec:java -Dexec.mainClass="io.scigraph.services.MainApplication" -Dexec.args="server /data/monarch-server-config.yaml"
RUN unzip /data/scigraph/SciGraph-services/target/scigraph-services-2.1-SNAPSHOT.zip -d /data
# TODO get rid of version
CMD java -jar /data/scigraph-services-2.1-SNAPSHOT/scigraph-services-2.1-SNAPSHOT.jar server /data/monarch-server-config.yaml
#CMD ls -al /data

EXPOSE 9000
